// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Contexts;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ThisDBContext))]
    [Migration("20230717154159_AddSwiftMassegesTableToDb")]
    partial class AddSwiftMassegesTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("WebApplication1.Models.SwiftMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Field4Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field5Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SwiftMessage");
                });

            modelBuilder.Entity("WebApplication1.Models.SwiftMessageChecksum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CHK")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SwiftMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SwiftMessageId")
                        .IsUnique();

                    b.ToTable("SwiftMessageChecksum");
                });

            modelBuilder.Entity("WebApplication1.Models.SwiftMessageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field20")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field21")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field79")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SwiftMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SwiftMessageId")
                        .IsUnique();

                    b.ToTable("SwiftMessageContent");
                });

            modelBuilder.Entity("WebApplication1.Models.SwiftMessageChecksum", b =>
                {
                    b.HasOne("WebApplication1.Models.SwiftMessage", "SwiftMessage")
                        .WithOne("Field5")
                        .HasForeignKey("WebApplication1.Models.SwiftMessageChecksum", "SwiftMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwiftMessage");
                });

            modelBuilder.Entity("WebApplication1.Models.SwiftMessageContent", b =>
                {
                    b.HasOne("WebApplication1.Models.SwiftMessage", "SwiftMessage")
                        .WithOne("Field4")
                        .HasForeignKey("WebApplication1.Models.SwiftMessageContent", "SwiftMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwiftMessage");
                });

            modelBuilder.Entity("WebApplication1.Models.SwiftMessage", b =>
                {
                    b.Navigation("Field4")
                        .IsRequired();

                    b.Navigation("Field5")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
